source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", ">= 3.9.0"

gem 'jekyll-feed', '>= 0.12.1'

gem "jekyll-assets", ">= 3.0.12"

gem 'autoprefixer-rails'
gem 'jekyll-autoprefixer'
